#!/usr/bin/env python

"""Run the power method."""

from nolina import power
from importlib import reload
reload(power)

d = 10
M = 100

A = power.random_matrix(d)
y = power.power_method(A, M)


print('Done')
